name: Periodic Health Check

on:
  push:
    branches:
      - master

jobs:
  periodic_health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Periodic Health Check
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://pure-beach-43727.herokuapp.com/health
          max-attempts: 5
          retry-delay: 5s
